### ISSUE TITLE
Develop initial API schema.

### ISSUE THREAD

**Issue by teymour-aldridge** [MLH-Fellowship/0.5.1-household#1]
We should work out how our REST API should work first!
I think we can use this as a base to co-ordinate everything and divide it up so that different people can do different things.

**Comment by gmelodie** [comment]
So I did a sketch of what would be nice to have on the design.

## Data Types
1. **Tasks**: The tasks you have on your house (e.g. doing dishes, cleaning living room, etc.)
    - **Points**: Each task will value a certain amount of points. This determines how hard the task generally is in comparison to others.
    - **Frequency**: This determines how often the task must be accomplished

2. **Periods**: Bigger/busier houses might need to be cleaned more frequently. *Period* defines how often each set of tasks must be done again. (weekly, monthly, etc.) Also, different periods when the house is used less (e.g. vacations) can also be created.

3. **Users**: The ones who must do the tasks
    - **List of tasks**: Each user has an initial list of tasks assigned to them
    - **Required task points**: The amount of task points the user has to accomplish in a given period
    - **Permissions**: Permissions to create, delete and update tasks and periods

## Dynamics
1. Doing tasks
    - Only the assigned user is able to do the task until it expires
    - When a task expires, other users can do it for bonus points
    - If user A completes an unexpired task assigned to user B, A doesn't get bonus points and task is marked as completed by user B

2. Spending bonus points
- Bonus points expire after a certain amount of time so that users cannot hold them for much long

## Actions
1. Add, remove, update **tasks**
2. Add, remove, update **users** and user information (list of tasks)
3. Add, remove, update **periods**

### Obs
- Maybe we could use some kind of gamification here to incentivize users doing tasks. Rank users according to:
    1. Longest task streak
    2. Most bonus points
    3. Most tasks in the current week

- For gamification, permissions and other trust mechanisms to work we would need to have authentication

- Notifications and calendar integration would be nice

**Comment by victorphoenix3** [comment]
We can add a feature for users to trade tasks.
Also, how are the tasks going to be distributed? Do the users get to pick?

**Comment by gmelodie** [comment]
@victorphoenix3 added your ideas and yes, tasks are picked by the users however they see fit. Here comes a bit of trust: users need to trust each other that no task will get unassigned and conflicts will be resolved by them (the app is not magic, it won't make house sharing problems disappear :smile:)

**Comment by victorphoenix3** [comment]
Will need to add registration/login feature

**Comment by victorphoenix3** [comment]
Also a group chat will be great

**Comment by teymour-aldridge** [comment]
Looks cool! My suggestion is that we could use Flask for the API (or FastAPI, it doesn't really matter) and SQLAlchemy (which is a Python ORM, for SQL databases.
Interestingly, Python also has bindings to the V8 runtime and can do server-side React rendering.

**Comment by gmelodie** [comment]
This discussion has been moved to #8. Closing.
